POST http://localhost:3004/api/user/register HTTP/1.1
Content-Type: application/json

{
    "username":"gfff123",
    "nickname":"Juana iguana",
    "urlImage":"juan.com",
    "password":"hola123"
}

###

POST http://localhost:3004/api/user/login HTTP/1.1
Content-Type: application/json

{
    "username":"pablo123",
    "password":"hola123"
}

###

GET http://localhost:3004/api/user/viewheader HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzIiwibmlja25hbWUiOiJKb3NlIHBhYmxvIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sInN1YiI6InBhYmxvMTIzIiwiaWF0IjoxNzQ2MDQxNDE5LCJleHAiOjE3NDYwNDUwMTl9.NC8F26sivfyeIMmwzja9CVcbtZPwuwSuujuOT1ZbFCTKOvyxzSmPXot84Rdd0X7w3XwDhM9NzDLO-atXZUZDTA

###

GET http://localhost:3004/api/user/findfriendheader?page=0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzIiwibmlja25hbWUiOiJKb3NlIHBhYmxvIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sInN1YiI6InBhYmxvMTIzIiwiaWF0IjoxNzQ2MDQxNDE5LCJleHAiOjE3NDYwNDUwMTl9.NC8F26sivfyeIMmwzja9CVcbtZPwuwSuujuOT1ZbFCTKOvyxzSmPXot84Rdd0X7w3XwDhM9NzDLO-atXZUZDTA

###

GET http://localhost:3004/api/message?userfriend=juan123 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzIiwibmlja25hbWUiOiJKb3NlIHBhYmxvIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sInN1YiI6InBhYmxvMTIzIiwiaWF0IjoxNzQ2MDQxNDE5LCJleHAiOjE3NDYwNDUwMTl9.NC8F26sivfyeIMmwzja9CVcbtZPwuwSuujuOT1ZbFCTKOvyxzSmPXot84Rdd0X7w3XwDhM9NzDLO-atXZUZDTA

###