spring.application.name=javaspringservice


jwt.secret.key=fjhkdsjgfkfdjgkfdjghfjghfduhguihug5uy43g5yu4g57yg476574g654g6435g6453g634tg6gt64gt43g4t36g436
server.port=3004

spring.datasource.url=jdbc:postgresql://localhost:5432/ejemplos
spring.datasource.username=pablo
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
